if(GTEST_FOUND)
  return()
endif()

find_package(PackageHandleStandardArgs REQUIRED)

find_path(GTEST_INCLUDE_DIRS gtest/gtest.h
    HINTS
        ENV GTEST_INCLUDE_PATH ${GTEST_INCLUDE_PATH}
        ENV GTEST_ROOT ${GTEST_ROOT}
    NO_DEFAULT_PATH
  )

if(GTEST_INCLUDE_DIRS)

    find_library (GTEST gtest PATHS ${GTEST_LIBRARY_PATH})

    if(GTEST AND GTEST_DEBUG)
      set(GTEST_LIBRARIES optimized ${GTEST} debug ${GTEST_DEBUG} )
    elseif(GTEST)
      set(GTEST_LIBRARIES ${GTEST})
    endif()
    
    set(GTEST_BOTH_LIBRARIES ${GTEST_LIBRARIES} ${GTEST_MAIN_LIBRARIES})
    
endif()

FIND_PACKAGE_HANDLE_STANDARD_ARGS(GTEST DEFAULT_MSG GTEST_INCLUDE_DIRS GTEST_LIBRARIES)

if (GTEST_FOUND AND VERBOSE)
    message(STATUS "GTEST_FOUND=${GTEST_FOUND}")
    message(STATUS "GTEST_INCLUDE_DIRS=${GTEST_INCLUDE_DIRS}")
    message(STATUS "GTEST_LIBRARIES=${GTEST_LIBRARIES}")
    message(STATUS "GTEST_MAIN_LIBRARIES=${GTEST_MAIN_LIBRARIES}")
    message(STATUS "GTEST_BOTH_LIBRARIES=${GTEST_BOTH_LIBRARIES}")
endif()
